apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscli
spec:
  selector:
    matchLabels:
      app: awscli
  template:
    metadata:
      labels:
        app: awscli
    spec:
      serviceAccount: pod-identity-demo
      containers:
      - name: awscli
        image: amazon/aws-cli
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
          - "sleep"
          - "604800"
        env:
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: pod-envs
              key: cluster_name
        - name: BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: pod-envs
              key: bucket_name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        volumeMounts:
        - mountPath: /mtn/envs
          name: pod-envs
          readOnly: true
      volumes:
      - name: pod-envs
        configMap:
          name: pod-envs
          defaultMode: 0755
        # restartPolicy: Always
