# Check node taints
# kubectl taint nodes ip-10-0-1-214.eu-west-1.compute.internal key1=value1:NoSchedule
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"