# Check node labels, if ip-10-0-1-181.eu-west-1.compute.internal isn't labeled type=test, add the label
# Apply the manifest, it should install the pods to just the desired node 
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  nodeSelector:
    type: test

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
spec:
  nodeName: ip-10-0-1-173.eu-west-1.compute.internal # schedule pod to specific node
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "100m"