# A rewrite ingress + two services + two deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go
  labels:
    app: hello-go
    type: appserver
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
      - name: hello-go
        imagePullPolicy: Always
        image: europe-north1-docker.pkg.dev/tuomaspal-sandbox/training/hello-http:0.0.2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: REDIS
            valueFrom:
              configMapKeyRef:
                name: redis-configmap
                key: redis-address
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: redis-configmap
                key: redis-port
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-secret
                key: redis-password