apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  redis-address: cmVkaXMtc2VydmljZQo=
  redis-port: NjM3OQo=
  redis-password: bXlfc3VwZXJfc2VjcmV0X3JlZGlzX3Bhc3N3b3JkCg==