# Scale the deployment by editing or:
# kubectl scale --replicas=3 -demo3.yaml
# kubectl scale --current-replicas=2 --replicas=3 deployment/my-nginx
# kubectl autoscale deployment my-nginx --cpu-percent=50 --min=1 --max=10
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
    type: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

