apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["/bin/echo"]
    args: ["$(MESSAGE)"]
    env: 
    - name: MESSAGE
      value: "Hello world!"
    resources:
      requests:
        memory: "64Mi"
        cpu: "1250m"
      limits:
        memory: "128Mi"
        cpu: "1500m"
  restartPolicy: OnFailure