 g# You can suspend your cronjob with:
# kubectl patch cronjobs hello -p '{"spec" : {"suspend" : true }}'
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  # Runs every minute
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            resources:
              requests:
                memory: "64Mi"
                cpu: "100m"
              limits:
                memory: "128Mi"
                cpu: "500m"            
          restartPolicy: OnFailure