# Health checks
# Liveness and Readiness
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: hello-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
      - image: redis:7.0.5
        name: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: 200Mi
            cpu: 100m
        startupProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          tcpSocket: 
            port: 6379
          initialDelaySeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["redis-cli", "ping", "|", "grep PONG"]
          initialDelaySeconds: 30
          timeoutSeconds: 10