apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tr-tuomas
  name: pod-monitor
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor
  namespace: tr-tuomas
subjects:
- kind: ServiceAccount
  name: demo-serviceaccount
roleRef:
  kind: Role
  name: pod-monitor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: sa-demo
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  serviceAccountName: demo-serviceaccount
