apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.mygroup.example.com
spec:
  group: mygroup.example.com         # API group
  versions:
    - name: v1
      served: true                   # Enable serving this version
      storage: true                  # Use this as the storage version
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                foo:
                  type: string        # Define a custom field `foo`
  scope: Namespaced                   # Resource will be namespace-scoped
  names:
    plural: examples                  # Plural name of the resource
    singular: example                 # Singular name of the resource
    kind: Example                     # Kind for the resource
    shortNames:
    - ex                              # Optional short name

